// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID              []byte             `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	PublicKey       []byte             `json:"public_key"`
	SignCount       int64              `json:"sign_count"`
	Transports      []string           `json:"transports"`
	AttestationType pgtype.Text        `json:"attestation_type"`
	Aaguid          uuid.NullUUID      `json:"aaguid"`
	Attestation     []byte             `json:"attestation"`
	Flags           []byte             `json:"flags"`
	CloneWarning    pgtype.Bool        `json:"clone_warning"`
	Attachment      pgtype.Text        `json:"attachment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
