// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCredential(ctx context.Context, arg AddCredentialParams) error
	GetUserByEmailOrId(ctx context.Context, arg GetUserByEmailOrIdParams) (GetUserByEmailOrIdRow, error)
	GetUserPasskeyCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error)
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
}

var _ Querier = (*Queries)(nil)
